version: '3'
services:
  db:
    platform: 'linux/x86_64'
    image: mysql
    restart: always
    cap_add:
      - SYS_NICE
    env_file: ./.env
    environment:
      MYSQL_ROOT_PASSWORD: $DB_PASSWORD
      MYSQL_DATABASE: $DB
      MYSQL_USER: $DB_USERNAME
    ports:
      - $MYSQL_LOCAL_PORT:$MYSQL_DOCKER_PORT
    volumes:
      - db-config:/etc/mysql
      - db-data:/var/lib/mysql
      - ./db/backup/files/:/data_backup/data
  bot:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: task-manager-bot
    env_file: ./.env
    ports:
      - "3000:3000"
    depends_on:
      - db
    links:
      - db
    stdin_open: true
    tty: true
    volumes: 
      - ./:/app/src/.

volumes:
  db-config:
  db-data:
